Added support for 'inherited' ACEs to 'chgrpacl' & 'chusracl', plus a minor fix for the new '-acelocal' & '-aceinherited' primaries in 'findacl'.

diff --git a/chgrpacl b/chgrpacl
--- a/chgrpacl
+++ b/chgrpacl
@@ -40,20 +40,32 @@ function main () {
 	local file
 	while IFS= read -r line; do
 		# parse the ACEs or filename
-		if [[ "$line" =~ ^\ ([0-9]+):\ (user|group):([A-Za-z0-9]+)\ (allow|deny)\ ([a-z_,]+)$ ]]; then
+		if [[ "$line" =~ ^\ ([0-9]+):\ ((user|group):)?([A-Za-z0-9._-]+)\ ((local|inherited)\ )?(allow|deny)\ ([a-z_,]+)$ ]]; then
 			local num="${BASH_REMATCH[1]}"
-			local type="${BASH_REMATCH[2]}"
-			local name="${BASH_REMATCH[3]}"
-			local grant="${BASH_REMATCH[4]}"
-			local permissions="${BASH_REMATCH[5]}"
+			local type="${BASH_REMATCH[3]}"
+			local name="${BASH_REMATCH[4]}"
+			local inherited="${BASH_REMATCH[6]}"
+			local grant="${BASH_REMATCH[7]}"
+			local permissions="${BASH_REMATCH[8]}"
 			
 			#echo "#: $num; TYPE: $type; NAME: $name; GRANT: $grant; PERMISSIONS: $permissions"
 			
 			# rewrite the ACL with the new group name
-			if chmod =a# ${num} "${type}:${new_group} ${grant} ${permissions}" "$file"; then
-				echo " ${num}: ${type}:${old_group} ${grant} ${permissions}  -->  ${num}: ${type}:${new_group} ${grant} ${permissions}"
+			local tmp_old_group="$old_group"
+			local tmp_new_group="$new_group"
+			if [ -n "$type" ]; then
+				tmp_old_group="${type}:${tmp_old_group}"
+				tmp_new_group="${type}:${tmp_new_group}"
+			fi
+			if [ "$inherited" = "inherited" ]; then
+				chmod =ai# ${num} "${tmp_new_group} ${grant} ${permissions}" "$file"
 			else
-				echo " ERROR! Unable to change ACE '${num}: ${type}:${old_group} ${grant} ${permissions}'!" 1>&2
+				chmod =a# ${num} "${tmp_new_group} ${grant} ${permissions}" "$file"
+			fi
+			if [ $? -eq 0 ]; then
+				echo " ${num}: ${tmp_old_group} ${inherited} ${grant} ${permissions}  -->  ${num}: ${tmp_new_group} ${inherited} ${grant} ${permissions}"
+			else
+				echo " ERROR! Unable to change ACE '${num}: ${tmp_old_group} ${inherited} ${grant} ${permissions}'!" 1>&2
 			fi
 		elif [[ "$line" =~ ^[^\ ] ]]; then
 			file="$line"
